import { BLOCK_TYPES } from '../blockTypes';
import { blockMsg } from './blockI18n';

export function getControlBlockDefinitions() {
  return [
    {
      type: BLOCK_TYPES.control.sleepS,
      message0: blockMsg('control.sleepS'),
      args0: [{ type: 'input_value', name: 'SECONDS', check: 'Number' }],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
      extensions: ['shape_statement'],
    },
    {
      type: BLOCK_TYPES.control.wait,
      message0: blockMsg('control.wait'),
      args0: [
        {
          type: 'input_value',
          name: 'CONDITION',
          check: 'Boolean',
        },
      ],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
      extensions: ['shape_statement'],
    },
    {
      type: BLOCK_TYPES.control.break,
      message0: blockMsg('control.break'),
      previousStatement: null,
      style: 'control_blocks',
      extensions: ['shape_end'],
    },
    {
      type: BLOCK_TYPES.control.whileTimes,
      message0: blockMsg('control.whileTimes'),
      message1: '%1',
      args0: [{ type: 'input_value', name: 'TIMES', check: 'Number' }],
      args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
      extensions: ['shape_statement'],
    },
    {
      type: BLOCK_TYPES.control.while,
      message0: blockMsg('control.while'),
      message1: '%1',
      args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
      extensions: ['shape_statement'],
    },
    {
      type: BLOCK_TYPES.control.if,
      message0: blockMsg('control.if'),
      message1: '%1',
      args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
      args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
      extensions: ['shape_statement'],
    },
    {
      type: BLOCK_TYPES.control.ifElse,
      message0: blockMsg('control.ifElse'),
      message1: '%1',
      message2: blockMsg('control.ifElseElse'),
      message3: '%1',
      args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
      args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
      args3: [{ type: 'input_statement', name: 'SUBSTACK2' }],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
      extensions: ['shape_statement'],
    },
    {
      type: BLOCK_TYPES.control.whileDo,
      message0: blockMsg('control.whileDo'),
      message1: '%1',
      args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
      args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
      extensions: ['shape_statement'],
    },
    {
      type: BLOCK_TYPES.control.stopExit,
      message0: blockMsg('control.stopExit'),
      previousStatement: null,
      nextStatement: null,
      style: 'control_blocks',
      extensions: ['shape_statement'],
    },
  ];
}
