import { BLOCK_TYPES } from '../blockTypes';


export const controlBlockDefinitions = [
  {
    type: BLOCK_TYPES.control.sleepS,
    message0: '等待 %1 秒',
    args0: [{ type: 'input_value', name: 'SECONDS', check: 'Number' }],
    previousStatement: null,
    nextStatement: null,
    style: 'control_blocks',
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.control.wait,
    message0: '等待 %1',
    args0: [
      {
        type: 'input_value',
        name: 'CONDITION',
        check: 'Boolean',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    style: 'control_blocks',
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.control.break,
    message0: '跳出循环',
    previousStatement: null,
    style: 'control_blocks',
    extensions: ['shape_end'],
  },
  {
    type: BLOCK_TYPES.control.whileTimes,
    message0: '重复执行 %1 次',
    message1: '%1',
    args0: [{ type: 'input_value', name: 'TIMES', check: 'Number' }],
    args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
    previousStatement: null,
    nextStatement: null,
    style: 'control_blocks',
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.control.while,
    message0: '重复执行',
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
    previousStatement: null,
    nextStatement: null,
    style: 'control_blocks',
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.control.if,
    message0: '如果 %1 那么',
    message1: '%1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
    previousStatement: null,
    nextStatement: null,
    style: 'control_blocks',
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.control.ifElse,
    message0: '如果 %1 那么',
    message1: '%1',
    message2: '否则',
    message3: '%1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
    args3: [{ type: 'input_statement', name: 'SUBSTACK2' }],
    previousStatement: null,
    nextStatement: null,
    style: 'control_blocks',
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.control.whileDo,
    message0: '重复执行直到 %1',
    message1: '%1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    args1: [{ type: 'input_statement', name: 'SUBSTACK' }],
    previousStatement: null,
    nextStatement: null,
    style: 'control_blocks',
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.control.stopExit,
    message0: '停止并且退出程序',
    previousStatement: null,
    nextStatement: null,
    style: 'control_blocks',
    extensions: ['shape_statement'],
  }
] as const;
