import { BLOCK_TYPES } from '../blockTypes';
import combinedMotor from '../../../assets/block/block_combined_motor.svg';
import separatorVertical from '../../../assets/block/block_separator_vertical.svg';
export const moveBlockDefinitions = [
  {
    type: BLOCK_TYPES.move.pair,
    message0: '%1 %2 将组合电机设置为 %3 转动方向为 %4',
    args0: [
      {
        type: 'field_image',
        src: combinedMotor,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
      {
        type: 'field_dropdown',
        name: 'DIRECTION',
        options: [
          ['左电机反向', '0'],
          ['右电机反向', '1'],
          ['全部反向', '2'],
          ['全部正向', '3'],
        ],
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    style: 'move_blocks',
  },
  {
    type: BLOCK_TYPES.move.moveSetStopModule,
    message0: '%1 %2 将组合电机设置为停止使 %3',
    args0: [
      {
        type: 'field_image',
        src: combinedMotor,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      {
        type: 'field_dropdown',
        name: 'DIRECTION',
        options: [
          ['惯性滑行', '0'],
          ['制动', '1'],
        ],
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    style: 'move_blocks',
  },
  {
    type: BLOCK_TYPES.move.movDirPowerSeconds,
    message0: '%1 %2 %3 以功率 %4 转动 %5 秒',
    args0: [
      {
        type: 'field_image',
        src: combinedMotor,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      {
        type: 'field_dropdown',
        name: 'DIRECTION',
        options: [
          ['前进', 'advance'],
          ['后退', 'retreat'],
          ['向左转', 'left'],
          ['向右转', 'right'],
        ],
      },
      { type: 'input_value', name: 'POWER', check: 'Number' },
      { type: 'input_value', name: 'SECONDS', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    inputsInline: true,
    style: 'move_blocks',
  },
  {
    type: BLOCK_TYPES.move.movDirPower,
    message0: '%1 %2 %3 以功率 %4 移动',
    args0: [
      {
        type: 'field_image',
        src: combinedMotor,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      {
        type: 'field_dropdown',
        name: 'DIRECTION',
        options: [
          ['前进', 'advance'],
          ['后退', 'retreat'],
          ['向左转', 'left'],
          ['向右转', 'right'],
        ],
      },
      { type: 'input_value', name: 'POWER', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    inputsInline: true,
    style: 'move_blocks',
  },
  {
    type: BLOCK_TYPES.move.movStop,
    message0: '%1 %2 停止运动',
    args0: [
      {
        type: 'field_image',
        src: combinedMotor,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    inputsInline: true,
    style: 'move_blocks',
  },
  {
    type: BLOCK_TYPES.move.movForPowerSeconds,
    message0: '%1 %2 以左功率 %3 %和右功率 %4 %移动 %5 秒',
    args0: [
      {
        type: 'field_image',
        src: combinedMotor,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      {
        type: 'input_value',
        name: 'LEFT_POWER',
        check: 'Number',
      },
      { type: 'input_value', name: 'RIGHT_POWER', check: 'Number' },
      { type: 'input_value', name: 'SECONDS', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    inputsInline: true,
    style: 'move_blocks',
  },
  {
    type: BLOCK_TYPES.move.movPower,
    message0: '%1 %2 以左功率 %3 %和右功率 %4 %移动',
    args0: [
      {
        type: 'field_image',
        src: combinedMotor,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      {
        type: 'input_value',
        name: 'LEFT_POWER',
        check: 'Number',
      },
      { type: 'input_value', name: 'RIGHT_POWER', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    inputsInline: true,
    style: 'move_blocks',
  },
  {
    type: BLOCK_TYPES.move.movFindLineInit,
    message0: '%1 %2 巡线参数初始化',
    args0: [
      {
        type: 'field_image',
        src: combinedMotor,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    inputsInline: true,
    style: 'move_blocks',
  },
  {
    type: BLOCK_TYPES.move.movFindLineRun,
    message0:
      '%1 %2 双巡线 左传感器 %3 右传感器 %4 左功率 %5 %右功率 %6 %KP %7 KD %8',
    args0: [
      {
        type: 'field_image',
        src: combinedMotor,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      {
        type: 'input_value',
        name: 'LEFT_SENSOR',
        check: 'Number',
      },
      {
        type: 'input_value',
        name: 'RIGHT_SENSOR',
        check: 'Number',
      },
      {
        type: 'input_value',
        name: 'LEFT_POWER',
        check: 'Number',
      },

      { type: 'input_value', name: 'RIGHT_POWER', check: 'Number' },
      { type: 'input_value', name: 'KP', check: 'Number' },
      { type: 'input_value', name: 'KD', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    inputsInline: true,
    style: 'move_blocks',
  },
] as const;
