import { BLOCK_TYPES } from '../blockTypes';
import touchIcon from '../../../assets/block/block_touch.svg';
import ultrasonicIcon from '../../../assets/block/block_ultrasonic.svg';
import distanceIcon from '../../../assets/block/block_gray_scale.svg';
import separatorVertical from '../../../assets/block/block_separator_vertical.svg';
import handleShankIcon from '../../../assets/block/block_handleShank.svg';
export const sensorBlockDefinitions = [
  {
    type: BLOCK_TYPES.sensor.touch_sensor.state,
    message0: '%1 %2触碰传感器 %3 被按下?',
    args0: [
      {
        type: 'field_image',
        src: touchIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
    ],
    style: 'sensors_blocks',
    extensions: ['output_boolean'],
  },
  {
    type: BLOCK_TYPES.sensor.gray_sensor.cmpLux,
    message0: '%1 %2 灰度传感器 %3 的反射光 %4 %5',
    args0: [
      {
        type: 'field_image',
        src: touchIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
      {
        type: 'field_dropdown',
        name: 'CMP',
        options: [
          ['>', '>'],
          ['<', '<'],
          ['=', '='],
        ],
      },
      { type: 'input_value', name: 'VALUE', check: 'Number' },
    ],
    style: 'sensors_blocks',
    extensions: ['output_boolean'],
  },
  {
    type: BLOCK_TYPES.sensor.gray_sensor.lux,
    message0: '%1 %2 灰度传感器 %3 的数值',
    args0: [
      {
        type: 'field_image',
        src: distanceIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
    ],
    style: 'sensors_blocks',
    extensions: ['output_number'],
  },
  {
    type: BLOCK_TYPES.sensor.gray_sensor.setColorThresholdValue,
    message0: '%1 %2 灰度传感器 %3 阈值设为 %4',
    args0: [
      {
        type: 'field_image',
        src: distanceIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
      { type: 'input_value', name: 'VALUE', check: 'Number' },
    ],
    style: 'sensors_blocks',
    previousStatement: null,
    nextStatement: null,
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.sensor.gray_sensor.luxState,
    message0: '%1 %2 灰度传感器 %3 是否触发',
    args0: [
      {
        type: 'field_image',
        src: distanceIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
    ],
    style: 'sensors_blocks',
    extensions: ['output_boolean'],
  },
  {
    type: BLOCK_TYPES.sensor.gray_sensor.oneCalibrate,
    message0: '%1 %2 校准 %3 灰度传感器 %4 秒',
    args0: [
      {
        type: 'field_image',
        src: distanceIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
      { type: 'input_value', name: 'SECONDS', check: 'Number' },
    ],
    style: 'sensors_blocks',
    previousStatement: null,
    nextStatement: null,
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.sensor.gray_sensor.twoCalibrate,
    message0: '%1 %2 %3 灰度传感器 %4 秒',
    args0: [
      {
        type: 'field_image',
        src: distanceIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
      { type: 'input_value', name: 'SECONDS', check: 'Number' },
    ],
    style: 'sensors_blocks',
    previousStatement: null,
    nextStatement: null,
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.sensor.ultrasonic_sensor.cmpValue,
    message0: '%1 %2 超声波传感器 %3 的距离是否 %4 %5 cm',
    args0: [
      {
        type: 'field_image',
        src: ultrasonicIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
      {
        type: 'field_dropdown',
        name: 'CMP',
        options: [
          ['>', '>'],
          ['<', '<'],
          ['=', '='],
        ],
      },
      { type: 'input_value', name: 'VALUE', check: 'Number' },
    ],
    style: 'sensors_blocks',
    extensions: ['output_boolean'],
  },
  {
    type: BLOCK_TYPES.sensor.ultrasonic_sensor.value,
    message0: '%1 %2 超声波传感器 %3 的数值',
    args0: [
      {
        type: 'field_image',
        src: ultrasonicIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'PORTS', check: 'Number' },
    ],
    style: 'sensors_blocks',
    extensions: ['output_number'],
  },
  {
    type: BLOCK_TYPES.sensor.remote_control_sensor.keyRemote,
    message0: '%1 %2 手柄 %3 是否 %4',
    args0: [
      {
        type: 'field_image',
        src: handleShankIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'HANDLESHANK', check: 'String' },
      {
        type: 'field_dropdown',
        name: 'STATE',
        options: [
          ['被按下', 'press'],
          ['未按下', 'unpress'],
        ],
      },
    ],
    style: 'sensors_blocks',
    extensions: ['output_boolean'],
  },
  {
    type: BLOCK_TYPES.sensor.remote_control_sensor.movSetAdvanceOffset,
    message0: '%1 %2 设置手柄前进偏移量为左 %3 右 %4',
    args0: [
      {
        type: 'field_image',
        src: handleShankIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'LEFT_OFFSET', check: 'Number' },
      { type: 'input_value', name: 'RIGHT_OFFSET', check: 'Number' },
    ],
    style: 'sensors_blocks',
    previousStatement: null,
    nextStatement: null,
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.sensor.remote_control_sensor.movSetRetreatOffset,
    message0: '%1 %2 设置手柄后退偏移量为左 %3 右 %4',
    args0: [
      {
        type: 'field_image',
        src: handleShankIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
      { type: 'input_value', name: 'LEFT_OFFSET', check: 'Number' },
      { type: 'input_value', name: 'RIGHT_OFFSET', check: 'Number' },
    ],
    style: 'sensors_blocks',
    previousStatement: null,
    nextStatement: null,
    extensions: ['shape_statement'],
  },
  {
    type: BLOCK_TYPES.sensor.remote_control_sensor.readAdcanceLeftOffset,
    message0: '%1 %2 读取前进左偏移量',
    args0: [
      {
        type: 'field_image',
        src: handleShankIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
    ],
    style: 'sensors_blocks',
    extensions: ['output_number'],
  },
  {
    type: BLOCK_TYPES.sensor.remote_control_sensor.readAdvanceRightOffset,
    message0: '%1 %2 读取前进右偏移量',
    args0: [
      {
        type: 'field_image',
        src: handleShankIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
    ],
    style: 'sensors_blocks',
    extensions: ['output_number'],
  },
  {
    type: BLOCK_TYPES.sensor.remote_control_sensor.readRetreatLeftOffset,
    message0: '%1 %2 读取后退左偏移量',
    args0: [
      {
        type: 'field_image',
        src: handleShankIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
    ],
    style: 'sensors_blocks',
    extensions: ['output_number'],
  },
  {
    type: BLOCK_TYPES.sensor.remote_control_sensor.readRetreatRightOffset,
    message0: '%1 %2 读取后退右偏移量',
    args0: [
      {
        type: 'field_image',
        src: handleShankIcon,
        width: 24,
        height: 24,
        alt: '*',
      },
      {
        type: 'field_image',
        src: separatorVertical,
        width: 2,
        height: 30,
        alt: '',
      },
    ],
    style: 'sensors_blocks',
    extensions: ['output_number'],
  },
  {
    type: BLOCK_TYPES.sensor.other.keyMast,
    message0: '主机 %1 按钮是否 %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'KEY',
        options: [
          ['左', 'left'],
          ['右', 'right'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'STATE',
        options: [
          ['被按下', '1'],
          ['未按下', '0'],
        ],
      },
    ],
    style: 'sensors_blocks',
    extensions: ['output_boolean'],
  },
  {
    type: BLOCK_TYPES.sensor.other.timer,
    message0: '计时器',
    style: 'sensors_blocks',
    extensions: ['output_number'],
  },
  {
    type: BLOCK_TYPES.sensor.other.resetTimer,
    message0: '重置计时器',
    style: 'sensors_blocks',
    previousStatement: null,
    nextStatement: null,
    extensions: ['shape_statement'],
  },
] as const;
